FROM tomcat:9-jdk11

WORKDIR /app

RUN apt-get update && apt-get install -y maven=3.6.3-1

COPY . /app

RUN mvn clean install

RUN cp target/GitHubFirst.war /usr/local/tomcat/webapps

CMD ["catalina.sh", "run"]
